### ISSUE TITLE
colorRGB wrong color

### ISSUE THREAD

**Issue by pckhib** [Daniel-t/MiLight_v6#4]
Hi,

I'm using the `zoneCtlRGBWFactory`.
If I try to set e.g. a red color with the `colorRGB` method, I get a pink color as a result.

`z1.command("colorRGB",[255,0,0])`

**Comment by mwittig** [comment]
@pckhib, you may also want to have a look at [node-milight-promise](https://www.npmjs.com/package/node-milight-promise). The API is somewhat less comfortable but highly flexible. It the legacy Milight (pre v6) controllers. I have also implemented some tweaks to fix the color circle mappings for some of the bulbs types.

**Comment by Daniel-t** [comment]
@pckhib Try setting the brightness to 100 at the same time.   I've noticed a lower brightness gives an paler shade.

**Comment by pckhib** [comment]
Thanks @mwittig, I'm now using node-milight-promise as suggested and it works fine.
@Daniel-t I'm sure I had the brightness at 100, but I will test again once I have time.
